services:
  mongodb:
    image: mongo:7
    container_name: pulse-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - pulse_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pulse

  redis:
    image: redis:7-alpine
    container_name: pulse-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - pulse_redis_data:/data

volumes:
  pulse_mongo_data:
  pulse_redis_data:
